# -*- coding: utf-8 -*-
"""fromscratchDict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18B6gzALlNdKBtMe_XBgRE7jPPIlRMa6J
"""


#since this wld be flask backend, I shall import -ok importing Response 
# coz the output on frontend is some html thing & not my url plain text
from flask import Flask, Response , jsonify

#jic
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

#i think app.route is just to create the url of the https page from which i fetch in .tsx
@app.route('/outputURL/<textFromUser>')
def outputURL(textFromUser):


  print(f"the query we got {textFromUser} ")
  #gonna kinda do embeddings then nearest neighbour serach which is like knn

  from sentence_transformers import SentenceTransformer, util
  import torch
  import pandas as pd
  import pickle

  dataset = pd.concat(map(pd.read_csv, ["/Users/deepamalika/SignBridge/app/scraped data/a.csv", "/Users/deepamalika/SignBridge/app/scraped data/b.csv", "/Users/deepamalika/SignBridge/app/scraped data/c.csv",
                                        "/Users/deepamalika/SignBridge/app/scraped data/d.csv", "/Users/deepamalika/SignBridge/app/scraped data/e.csv", "/Users/deepamalika/SignBridge/app/scraped data/f.csv",
                                        "/Users/deepamalika/SignBridge/app/scraped data/g.csv", "/Users/deepamalika/SignBridge/app/scraped data/h.csv", "/Users/deepamalika/SignBridge/app/scraped data/i.csv",
                                        "/Users/deepamalika/SignBridge/app/scraped data/j.csv", "/Users/deepamalika/SignBridge/app/scraped data/k.csv", "/Users/deepamalika/SignBridge/app/scraped data/l.csv",
                                        "/Users/deepamalika/SignBridge/app/scraped data/m.csv", "/Users/deepamalika/SignBridge/app/scraped data/n.csv", "/Users/deepamalika/SignBridge/app/scraped data/p.csv",
                                        "/Users/deepamalika/SignBridge/app/scraped data/q.csv", "/Users/deepamalika/SignBridge/app/scraped data/r.csv", "/Users/deepamalika/SignBridge/app/scraped data/s.csv",
                                        "/Users/deepamalika/SignBridge/app/scraped data/t.csv", "/Users/deepamalika/SignBridge/app/scraped data/u.csv",
                                        "/Users/deepamalika/SignBridge/app/scraped data/v.csv", "/Users/deepamalika/SignBridge/app/scraped data/w.csv", "/Users/deepamalika/SignBridge/app/scraped data/x.csv",
                                        "/Users/deepamalika/SignBridge/app/scraped data/y.csv", "/Users/deepamalika/SignBridge/app/scraped data/z.csv"]))

  dataset = dataset.dropna()
  dataset['id'] = dataset.index
  dataset.columns = dataset.columns.str.strip()
  dataset['word'].str.strip()
  dataset['videoURL'].str.strip()

  model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2', device="cpu")
  #to list coz i dw a dataframe i want the list of words to encode
  embeddings = model.encode(dataset["word"].to_list(), show_progress_bar=True)

  ''''
  #commenting out this print codes
  pd.set_option('display.max_rows',5)
  print(dataset)
  '''

  #if user queries, I need to embed it then nearest neigh similarity
  '''
  user_queries = ["I am happy",
                  "Thank you",
                  "How are you",
                  "I have eaten",
                  "Good morning",
                  "See you soon",
                  "Where do you live",
                  "what is your name",
                  "I am sick",
                  "I love dogs a lot",
                  "you are very sweet"]
  '''
  user_queries = [textFromUser] #textfromuser coz it is a param in def, it is default string
  #i shall split each sentence to ind words & generally my file dta is lowercase }nah my model shld be gd enough
  #tokenised_queries = list(map(str.split,user_queries))
  #queries_embeddings = model.encode(tokenised_queries, convert_to_tesnor=True)

  queries_embeddings = model.encode(user_queries, convert_to_tensor=True)

  #ig trying out nearest neighbour based classif
  '''
   #OMG NEARESTNEIGH EXPECTS NUMPY ARRAY so self numpy was 
   tryna happen but my embedding not cpu causing error}found forum soln
   to set model as cpu
   '''
  import numpy as np
  from sklearn.neighbors import NearestNeighbors             

  #ohh i must fit my training data on the nearest neighbours 1st
  neigh = NearestNeighbors(n_neighbors=1, metric='euclidean')
  neigh.fit(embeddings)
  #similar to X-train, Y_train = 1 func, since .kneigh gives dist & ind
  #btw recall that we get 2D arrays for dist and index
  dist, index = neigh.kneighbors(queries_embeddings)
  #for i,qElem in enumerate(user_queries):
  #  print(dataset['videoURL'].to_list()[index[i][0]])

  print(dataset['videoURL'].to_list()[index[0][0]])
  #print(index)
  #return dataset['videoURL'].to_list()[index[0][0]]
  vidUR = dataset['videoURL'].to_list()[index[0][0]]
  return Response(vidUR, mimetype='text/plain', content_type='text/plain')
  #return jsonify({'url': vidUR})

if __name__ == "__main__":
  app.run(host='0.0.0.0', port=8000, debug=True) #changed 5000 to 8000 here and on index fetch