# -*- coding: utf-8 -*-
"""fromscratchDict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18B6gzALlNdKBtMe_XBgRE7jPPIlRMa6J
"""


#since this wld be flask backend, I shall import -ok importing Response 
# coz the output on frontend is some html thing & not my url plain text
from flask import Flask, Response , jsonify

#jic
from flask_cors import CORS


app = Flask(__name__)
CORS(app)

#i think app.route is just to create the url of the https page from which i fetch in .tsx
@app.route('/outputURL/<textFromUser>')
def outputURL(textFromUser):

  print(f"the query we got {textFromUser} ")
  #gonna kinda do embeddings then nearest neighbour serach which is like knn

  from sentence_transformers import SentenceTransformer, util
  import torch
  import pandas as pd
  import pickle

  dataset = pd.concat(map(pd.read_csv, ["https://scrapedcsvfiles.blob.core.windows.net/26csvs/a.csv",
                                        "https://scrapedcsvfiles.blob.core.windows.net/26csvs/b.csv",
                                        "https://scrapedcsvfiles.blob.core.windows.net/26csvs/c.csv",
                                        "https://scrapedcsvfiles.blob.core.windows.net/26csvs/d.csv",
                                        "https://scrapedcsvfiles.blob.core.windows.net/26csvs/e.csv",
                                        "https://scrapedcsvfiles.blob.core.windows.net/26csvs/f.csv",
                                        "https://scrapedcsvfiles.blob.core.windows.net/26csvs/g.csv",
                                        "https://scrapedcsvfiles.blob.core.windows.net/26csvs/h.csv",
                                        "https://scrapedcsvfiles.blob.core.windows.net/26csvs/i.csv",
                                        "https://scrapedcsvfiles.blob.core.windows.net/26csvs/j.csv",
                                        "https://scrapedcsvfiles.blob.core.windows.net/26csvs/k.csv",
                                        "https://scrapedcsvfiles.blob.core.windows.net/26csvs/l.csv",
                                        "https://scrapedcsvfiles.blob.core.windows.net/26csvs/m.csv",
                                        "https://scrapedcsvfiles.blob.core.windows.net/26csvs/n.csv",
                                        "https://scrapedcsvfiles.blob.core.windows.net/26csvs/o.csv",
                                        "https://scrapedcsvfiles.blob.core.windows.net/26csvs/p.csv",
                                        "https://scrapedcsvfiles.blob.core.windows.net/26csvs/q.csv",
                                        "https://scrapedcsvfiles.blob.core.windows.net/26csvs/r.csv",
                                        "https://scrapedcsvfiles.blob.core.windows.net/26csvs/s.csv",
                                        "https://scrapedcsvfiles.blob.core.windows.net/26csvs/t.csv",
                                        "https://scrapedcsvfiles.blob.core.windows.net/26csvs/u.csv",
                                        "https://scrapedcsvfiles.blob.core.windows.net/26csvs/v.csv",
                                        "https://scrapedcsvfiles.blob.core.windows.net/26csvs/w.csv",
                                        "https://scrapedcsvfiles.blob.core.windows.net/26csvs/x.csv",
                                        "https://scrapedcsvfiles.blob.core.windows.net/26csvs/y.csv",
                                        "https://scrapedcsvfiles.blob.core.windows.net/26csvs/z.csv"
                                        ]))

  dataset = dataset.dropna()
  dataset['id'] = dataset.index
  dataset.columns = dataset.columns.str.strip()
  dataset['word'].str.strip()
  dataset['videoURL'].str.strip()

  #model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2', device="cpu")
  #doing the following to avoid cannot copy out meta tensor error on azure
  model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')
  model = model.to('cpu')



  #to list coz i dw a dataframe i want the list of words to encode
  embeddings = model.encode(dataset["word"].to_list(), show_progress_bar=True)

  ''''
  #commenting out this print codes
  pd.set_option('display.max_rows',5)
  print(dataset)
  '''

  #if user queries, I need to embed it then nearest neigh similarity
  '''
  user_queries = ["I am happy",
                  "Thank you",
                  "How are you",
                  "I have eaten",
                  "Good morning",
                  "See you soon",
                  "Where do you live",
                  "what is your name",
                  "I am sick",
                  "I love dogs a lot",
                  "you are very sweet"]
  '''
  user_queries = [textFromUser] #textfromuser coz it is a param in def, it is default string
  #split sentence to ind words? }nah my model shld be gd enough
  #tokenised_queries = list(map(str.split,user_queries))
  #queries_embeddings = model.encode(tokenised_queries, convert_to_tesnor=True)

  queries_embeddings = model.encode(user_queries, convert_to_tensor=True)

  #ig trying out nearest neighbour based classif
  '''
   #OMG NEARESTNEIGH EXPECTS NUMPY ARRAY so self numpy was 
   tryna happen but my embedding not cpu causing error}found forum soln
   to set model as cpu
   '''
  import numpy as np
  from sklearn.neighbors import NearestNeighbors             

  #ohh i must fit my training data on the nearest neighbours 1st
  neigh = NearestNeighbors(n_neighbors=1, metric='euclidean')
  neigh.fit(embeddings)
  #similar to X-train, Y_train = 1 func, since .kneigh gives dist & ind
  #btw recall that we get 2D arrays for dist and index
  dist, index = neigh.kneighbors(queries_embeddings)
  #for i,qElem in enumerate(user_queries):
  #  print(dataset['videoURL'].to_list()[index[i][0]])

  print(dataset['videoURL'].to_list()[index[0][0]])
  #print(index)
  #return dataset['videoURL'].to_list()[index[0][0]]
  vidUR = dataset['videoURL'].to_list()[index[0][0]]
  return Response(vidUR, mimetype='text/plain', content_type='text/plain')
  #return jsonify({'url': vidUR})

if __name__ == "__main__":
  app.run(host='0.0.0.0', port=8000, debug=True) #changed 5000 to 8000 here and on index fetch